/* What is the total revenue generated by top customers? */
SELECT
    c.name,
    SUM(total_price) AS revenue
FROM
    fact_table f
JOIN customer_dim c ON f.customer_key = c.customer_key
GROUP BY
    c.name
ORDER BY
    revenue DESC
LIMIT 10;

/* What is the purchase frequency and total revenue for top customers? */
SELECT
    c.name,
    COUNT(DISTINCT f.customer_key) AS purchase_frequency,
    SUM(total_price) AS revenue
FROM
    fact_table f
JOIN customer_dim c ON f.customer_key = c.customer_key
GROUP BY
    c.name
ORDER BY
    purchase_frequency DESC
LIMIT 10;


/* Are there significant regional differences in customer behavior? */
SELECT
	s.state,
	COUNT(DISTINCT f.Customer_key) AS purchase_frequency,
	SUM(total_price) AS sales
FROM
	fact_table f
JOIN store_dim s ON f.store_key = s.store_key 
GROUP BY
	s.state
ORDER BY
	purchase_frequency DESC;


/* What is the revenue contribution and purchase frequency of the top 10 customers? */
WITH total_revenue AS (
    SELECT SUM(total_price) AS total_sales
    FROM fact_table
),
customer_stats AS (
    SELECT
        c.customer_key,
        c.name,
        COUNT(f.payment_key) AS purchase_frequency,
        SUM(f.total_price) AS customer_revenue
    FROM
        fact_table f
    JOIN customer_dim c ON f.customer_key = c.customer_key
    GROUP BY
        c.customer_key, c.name
)
SELECT
    cs.name AS customer_name,
    cs.customer_revenue AS revenue_generated,
    CONCAT(ROUND((cs.customer_revenue / tr.total_sales) * 100, 2), '%') AS revenue_percentage,
    cs.purchase_frequency AS purchase_count
FROM
    customer_stats cs
CROSS JOIN total_revenue tr
ORDER BY
    cs.customer_revenue DESC
LIMIT 10;



